### PR TITLE
Fix flow::any constructor bug

### PR DESCRIPTION
**Pull request by nRewik**

### CODE REVIEW

**Comment by kittinunf** [comment]
:+1:  Straight :ship:  Can you also delete this for me?

https://github.com/taskworld/flowcpp/blob/master/main.cpp#L76

**Comment by kittinunf** [comment]
I no longer encounter this bug in the master branch. Do you remember what causes this?

**Comment by nRewik** [comment]
It's happened in tw-chat. When we create an action that has meta and payload of `flow::any` type without constructor.

**Comment by kittinunf** [comment]
Argh, it doesn't make sense to me at all. It works just fine in this repo.  Let's find out the actual root cause of this.

**Pull request closed without merging**
